import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { AddressDataType } from '../stories/AddressDetails'
import 'leaflet/dist/leaflet.css';

const inter = Inter({ subsets: ['latin'] })

import dynamic from 'next/dynamic'
import geolocateAddress from '../sharedLogic/geolocate'
const DynamicMap = dynamic(() => import('../stories/TrackerPage'), {
  ssr: false
})



export async function getServerSideProps() {
  //first access, run on server
  const address = await geolocateAddress()
  return {
    props: {
      address
    }
  }


}

export default function Home(props: { address: AddressDataType }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DynamicMap initialAddress={props.address} />
      </main>
    </>
  )
}
