import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { SearchBar } from '../stories/SearchBar'
import AddressDetails from '../stories/AddressDetails'
// import MapView from '../stories/MapView'
import 'leaflet/dist/leaflet.css';

import dynamic from 'next/dynamic'
const DynamicMap = dynamic(() => import('../stories/MapView'), {
  ssr: false
})
const inter = Inter({ subsets: ['latin'] })

const address = {
  ipAddress: "192.212.174.101",
  location: "Brooklyn, NY, 10001",
  timezone: "UTC -05:00",
  isp: "SpaceX Starlink"
}
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SearchBar ></SearchBar>
        <AddressDetails address={address} ></AddressDetails>
        <DynamicMap address={address}></DynamicMap>
      </main>
    </>
  )
}
